name: ci-node

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  test-node:
    name: test-node
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --package-lock=false
      - run: npm run lint
      - run: npm run test
      - run: npm run build
